language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "lint"
# command to install dependencies
install: "pip install -r requirements_dev.txt"

# command to run tests
script: python setup.py test

matrix:
    include:
        - python: "lint"
          script: "flake8 requests_staticmock/ tests --max-line-length=90"
after_success:
  - coveralls